- .gitignore
- src/main/resources/org/mybatis/jpetstore/persistence/AccountMapper.xml
Fixed boolean to integer mapping when inserting or updating an account.
> Fix boolean to integer mapping

- .gitignore
Add .idea at .gitignore for IDEA user.
Please merge this.
> Add .idea at .gitignore

- README.md
- src/main/webapp/WEB-INF/applicationContext.xml
- src/main/webapp/WEB-INF/web.xml
- src/site/es/xdoc/index.xml
- src/site/ja/xdoc/index.xml
- src/site/ko/xdoc/index.xml
- src/site/xdoc/index.xml
I've polished some configuration and documentations for Spring.
* Remove version into namespace location
* Fix comment for transaction manager
* Modify to use `<mybatis:scan>` tag instead of `MapperScannerConfigurer `
* Remove redundant configuration for `ContextLoaderListener`  at `web.xml`
* Update documents of maven site
* Update `README.md`
Please review.
Thanks.
> Polishing Spring configurations

- pom.xml
> Update to HSQLDB 2.3.4

- pom.xml
> Upgrade to Spring 4.3.2.RELEASE

- pom.xml
> Upgrade to Spring 4.3.3.RELEASE

- README.md
- pom.xml
> Modify to use cargo-maven2-plugin instead of tomcat-maven-plugin

- pom.xml
Mockito 2.2 has been released.
> Upgrade to Mockto 2.2.2

- pom.xml
> Upgrade to Mockito 2.2.7

- pom.xml
> Update Spring 4.3.4.RELEASE

- pom.xml
> Update Mockito 2.2.15

- pom.xml
> Update Cargo mavne2 plugin 1.6.1

- pom.xml
* 9.0.0.M13
* 8.5.8
* 8.0.39
* 7.0.73
> Update Tomcat for cargo

- README.md
I've added the link to new implementation of JPetstore used the MyBatis Spring Boot Starter.
> Introduce new implementation of JPetstore used the MyBatis Spring Boot Starter

- pom.xml
I've updated to latest versions.
> Upgrade to Tomcat 9.0.0.M15 and 8.5.9

- .gitignore
- .travis.yml
- README.md
- pom.xml
- src/test/java/org/mybatis/jpetstore/ScreenTransitionIT.java
> Add integration tests

- .gitignore
- .travis.yml
- README.md
- pom.xml
- src/test/java/org/mybatis/jpetstore/ScreenTransitionIT.java
- src/test/resources/webdrivermanager.properties
> Change to use WebDriverManager instead of maven-download-plugin for downloading geckodriver

- pom.xml
> [pom] Update mybatis-parent to 29 - fixes #110

- pom.xml
See gh-133
I've upgraded the spring version to 5.0.3.RELEASE.
This change is only library version up. 
WDYT?
> Support Spring 5

- .travis.yml
- README.md
- pom.xml
> Support JDK10 on Travis CI

- .travis.yml
- travis/after_success.sh
> Support integration test for all application server on Travis CI

- src/test/java/org/mybatis/jpetstore/web/actions/AccountActionBeanTest.java
- src/test/java/org/mybatis/jpetstore/web/actions/CatalogActionBeanTest.java
- src/test/java/org/mybatis/jpetstore/web/actions/OrderActionBeanTest.java
Hi. I've analysed your codebase and noticed that it is not fully tested.
I've written some tests for the methods in the following classes with the help of Diffblue Cover:
- org.mybatis.jpetstore.web
Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important in a subsequent PR.
> Add Unit Tests for classes in org.mybatis.jpetstore.web

- src/main/webapp/WEB-INF/jsp/cart/Cart.jsp
- src/test/java/org/mybatis/jpetstore/ScreenTransitionIT.java
Fixed the item to be removed that  didn't be received by the server, so it will end up in an error from the second remove
> Fix remove items from Cart

- src/main/webapp/css/jpetstore.css
- src/test/java/org/mybatis/jpetstore/web/actions/CatalogActionBeanTest.java
As we were testing a pipeline we ran into some easy-to-fix findings noticed by SonarQube.
> Fix static analysis findings

- pom.xml
- src/test/java/org/mybatis/jpetstore/ScreenTransitionIT.java
- src/test/java/org/mybatis/jpetstore/web/actions/CatalogActionBeanTest.java
> Upgrade to Selenide 5.15.1

- pom.xml
- tomcat 9.0.70
- tomcat 8.5.84
- tomee 8.0.13
- wildfly 26.1.2.final
- liberty 22.0.0.12 for ee7 and ee8
- jetty 9.4.50.v20221201 (prior was incorrect setting)
> [pom] Update container versions

- .env
- .gitignore
- Dockerfile
- README.md
- docker-compose.yaml
- pom.xml
- src/main/resources/database/jpetstore-hsqldb-data.sql
- src/main/webapp/WEB-INF/applicationContext.xml
- Add Dockerfile for building the image of the application
- Add docker-compose.yml for deploying the application using multiple containers
- Update READme to briefly explain how to run the application on Docker
> Add: Add Dockerfile and docker-compose.yml for deployment

- .github/workflows/site.yaml
- pom.xml
- src/site/site.xml
- src/site/site_es.xml
- src/site/site_ja.xml
- src/site/site_ko.xml
Changes replicated from https://github.com/mybatis/cdi/pull/423
> Change site deploy
